http:
#region routers
  routers:
    edomi-rtr:
      entryPoints:
        - "websecure"
      rule: "Host(`edomi.my-domain.de`)*
      middlewares:
        - default-headers
      tls:
        certResolver: servercow
        domains:
          - main: "edomi.my-domain.de"
        options: "edomi-user-cert"
      service: edomi-sevi
    edomi-ws:
      entrypoints:
        - "edomiws"
      rule: "Host(`edomi.my-domain.de`) && PathPrefix(`/visu/`)"
      middlewares:
        - edomi-websocket
      tls:
        certResolver: servercow
        domains:
          - main: "edomi.my-domain.de"
        options: "edomi-user-cert"
      service: edomi-visu-sevi
    alexa-rtr:
      entryPoints:
        - "websecure"
      rule: "Host(`alexa.my-domain.de`)"
      middlewares:
        - default-headers
        - alexa-redirect
      tls:
        certResolver: servercow
        domains:
          - main: "alexa.my-domain.de"
      service: alexa-sevi
#endregion routers

#region services
  services:
    edomi-sevi:
      loadBalancer:
        servers:
          - url: "http://192.168.0.11"
        passHostHeader: true
    edomi-visu-sevi:
      loadBalancer:
        servers:
            - url: "http://192.168.0.11:8080"
        passHostHeader: true
    alexa-sevi:
      loadBalancer:
        servers:
          - url: "http://192.168.0.11"
        passHostHeader: true
#endregion

#region middleware
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: http
    edomi-websocket:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: ws
          X-Forwarded-Port: 8080
    alexa-redirect:
      replacePathRegex:
        regex: "^/edomi/(.*)"
        replacement: "/admin/lbs/alexa/$1"
#endregion

#region TLS Options
tls:
  options:
    edomi-user-cert:
      clientAuth:
        caFiles:
          - /ca.crt
        clientAuthType: RequireAndVerifyClientCert
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
#endregion